#############################################################################
# Makefile for building: timetable
<<<<<<< HEAD
# Generated by qmake (2.01a) (Qt 4.7.2) on: ?? ????. 28 19:15:05 2011
=======
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? 27. ??? 20:56:49 2011
>>>>>>> john
# Project:  timetable.pro
# Template: app
# Command: c:\Qt\2010.05\qt\bin\qmake.exe -o Makefile timetable.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\Qt\2010.05\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
<<<<<<< HEAD
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		authorization.cpp \
		settings.cpp \
		order_details.cpp \
		places.cpp \
		services.cpp \
		users.cpp moc_mainwindow.cpp \
		moc_authorization.cpp \
		moc_settings.cpp \
		moc_order_details.cpp \
		moc_places.cpp \
		moc_services.cpp \
		moc_users.cpp
OBJECTS       = main.o \
		mainwindow.o \
		authorization.o \
		settings.o \
		order_details.o \
		places.o \
		services.o \
		users.o \
		moc_mainwindow.o \
		moc_authorization.o \
		moc_settings.o \
		moc_order_details.o \
		moc_places.o \
		moc_services.o \
		moc_users.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		timetable.pro
QMAKE_TARGET  = timetable
DESTDIR       = 
TARGET        = timetable

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_settings.h ui_order_details.h ui_places.h ui_services.h ui_users.h ui_authorization.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: timetable.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile timetable.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile timetable.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/timetable1.0.0 || $(MKDIR) .tmp/timetable1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/timetable1.0.0/ && $(COPY_FILE) --parents mainwindow.h authorization.h settings.h order_details.h places.h services.h users.h .tmp/timetable1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp authorization.cpp settings.cpp order_details.cpp places.cpp services.cpp users.cpp .tmp/timetable1.0.0/ && $(COPY_FILE) --parents mainwindow.ui settings.ui order_details.ui places.ui services.ui users.ui authorization.ui .tmp/timetable1.0.0/ && (cd `dirname .tmp/timetable1.0.0` && $(TAR) timetable1.0.0.tar timetable1.0.0 && $(COMPRESS) timetable1.0.0.tar) && $(MOVE) `dirname .tmp/timetable1.0.0`/timetable1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/timetable1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
=======
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: timetable.pro  ../../Qt/2010.05/qt/mkspecs/default/qmake.conf ../../Qt/2010.05/qt/mkspecs/qconfig.pri \
		../../Qt/2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		../../Qt/2010.05/qt/mkspecs/features/qt_functions.prf \
		../../Qt/2010.05/qt/mkspecs/features/qt_config.prf \
		../../Qt/2010.05/qt/mkspecs/features/exclusive_builds.prf \
		../../Qt/2010.05/qt/mkspecs/features/default_pre.prf \
		../../Qt/2010.05/qt/mkspecs/features/win32/default_pre.prf \
		../../Qt/2010.05/qt/mkspecs/features/debug.prf \
		../../Qt/2010.05/qt/mkspecs/features/debug_and_release.prf \
		../../Qt/2010.05/qt/mkspecs/features/default_post.prf \
		../../Qt/2010.05/qt/mkspecs/features/win32/default_post.prf \
		../../Qt/2010.05/qt/mkspecs/features/win32/rtti.prf \
		../../Qt/2010.05/qt/mkspecs/features/win32/exceptions.prf \
		../../Qt/2010.05/qt/mkspecs/features/win32/stl.prf \
		../../Qt/2010.05/qt/mkspecs/features/shared.prf \
		../../Qt/2010.05/qt/mkspecs/features/warn_on.prf \
		../../Qt/2010.05/qt/mkspecs/features/qt.prf \
		../../Qt/2010.05/qt/mkspecs/features/win32/thread.prf \
		../../Qt/2010.05/qt/mkspecs/features/moc.prf \
		../../Qt/2010.05/qt/mkspecs/features/win32/windows.prf \
		../../Qt/2010.05/qt/mkspecs/features/resources.prf \
		../../Qt/2010.05/qt/mkspecs/features/uic.prf \
		../../Qt/2010.05/qt/mkspecs/features/yacc.prf \
		../../Qt/2010.05/qt/mkspecs/features/lex.prf \
		../../Qt/2010.05/qt/mkspecs/features/include_source_dir.prf \
		c:/Qt/2010.05/qt/lib/qtmaind.prl
	$(QMAKE) -o Makefile timetable.pro
..\..\Qt\2010.05\qt\mkspecs\qconfig.pri:
..\..\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri:
..\..\Qt\2010.05\qt\mkspecs\features\qt_functions.prf:
..\..\Qt\2010.05\qt\mkspecs\features\qt_config.prf:
..\..\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf:
..\..\Qt\2010.05\qt\mkspecs\features\default_pre.prf:
..\..\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf:
..\..\Qt\2010.05\qt\mkspecs\features\debug.prf:
..\..\Qt\2010.05\qt\mkspecs\features\debug_and_release.prf:
..\..\Qt\2010.05\qt\mkspecs\features\default_post.prf:
..\..\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf:
..\..\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf:
..\..\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf:
..\..\Qt\2010.05\qt\mkspecs\features\win32\stl.prf:
..\..\Qt\2010.05\qt\mkspecs\features\shared.prf:
..\..\Qt\2010.05\qt\mkspecs\features\warn_on.prf:
..\..\Qt\2010.05\qt\mkspecs\features\qt.prf:
..\..\Qt\2010.05\qt\mkspecs\features\win32\thread.prf:
..\..\Qt\2010.05\qt\mkspecs\features\moc.prf:
..\..\Qt\2010.05\qt\mkspecs\features\win32\windows.prf:
..\..\Qt\2010.05\qt\mkspecs\features\resources.prf:
..\..\Qt\2010.05\qt\mkspecs\features\uic.prf:
..\..\Qt\2010.05\qt\mkspecs\features\yacc.prf:
..\..\Qt\2010.05\qt\mkspecs\features\lex.prf:
..\..\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf:
c:\Qt\2010.05\qt\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile timetable.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
>>>>>>> john
	-$(DEL_FILE) Makefile

check: first

<<<<<<< HEAD
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_authorization.cpp moc_settings.cpp moc_order_details.cpp moc_places.cpp moc_services.cpp moc_users.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_authorization.cpp moc_settings.cpp moc_order_details.cpp moc_places.cpp moc_services.cpp moc_users.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_authorization.cpp: authorization.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) authorization.h -o moc_authorization.cpp

moc_settings.cpp: settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settings.h -o moc_settings.cpp

moc_order_details.cpp: order_details.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) order_details.h -o moc_order_details.cpp

moc_places.cpp: places.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) places.h -o moc_places.cpp

moc_services.cpp: services.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) services.h -o moc_services.cpp

moc_users.cpp: users.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) users.h -o moc_users.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_settings.h ui_order_details.h ui_places.h ui_services.h ui_users.h ui_authorization.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_settings.h ui_order_details.h ui_places.h ui_services.h ui_users.h ui_authorization.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_settings.h: settings.ui
	/usr/bin/uic-qt4 settings.ui -o ui_settings.h

ui_order_details.h: order_details.ui
	/usr/bin/uic-qt4 order_details.ui -o ui_order_details.h

ui_places.h: places.ui
	/usr/bin/uic-qt4 places.ui -o ui_places.h

ui_services.h: services.ui
	/usr/bin/uic-qt4 services.ui -o ui_services.h

ui_users.h: users.ui
	/usr/bin/uic-qt4 users.ui -o ui_users.h

ui_authorization.h: authorization.ui
	/usr/bin/uic-qt4 authorization.ui -o ui_authorization.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		authorization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		settings.h \
		places.h \
		users.h \
		services.h \
		authorization.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

authorization.o: authorization.cpp authorization.h \
		ui_authorization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o authorization.o authorization.cpp

settings.o: settings.cpp settings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

order_details.o: order_details.cpp order_details.h \
		ui_order_details.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o order_details.o order_details.cpp

places.o: places.cpp places.h \
		ui_places.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o places.o places.cpp

services.o: services.cpp services.h \
		ui_services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o services.o services.cpp

users.o: users.cpp users.h \
		ui_users.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o users.o users.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_authorization.o: moc_authorization.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_authorization.o moc_authorization.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_order_details.o: moc_order_details.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_order_details.o moc_order_details.cpp

moc_places.o: moc_places.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_places.o moc_places.cpp

moc_services.o: moc_services.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_services.o moc_services.cpp

moc_users.o: moc_users.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_users.o moc_users.cpp

####### Install

install:   FORCE

uninstall:   FORCE

=======
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
>>>>>>> john
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
