#############################################################################
# Makefile for building: timetable
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ???. 27 09:33:53 2011
# Project:  timetable.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile timetable.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		authorization.cpp \
		settings.cpp \
		order_details.cpp \
		places.cpp \
		services.cpp \
		users.cpp \
		mheader.cpp moc_mainwindow.cpp \
		moc_authorization.cpp \
		moc_settings.cpp \
		moc_order_details.cpp \
		moc_places.cpp \
		moc_services.cpp \
		moc_mheader.cpp
OBJECTS       = main.o \
		mainwindow.o \
		authorization.o \
		settings.o \
		order_details.o \
		places.o \
		services.o \
		users.o \
		mheader.o \
		moc_mainwindow.o \
		moc_authorization.o \
		moc_settings.o \
		moc_order_details.o \
		moc_places.o \
		moc_services.o \
		moc_mheader.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		timetable.pro
QMAKE_TARGET  = timetable
DESTDIR       = 
TARGET        = timetable

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_settings.h ui_order_details.h ui_places.h ui_services.h ui_users.h ui_authorization.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: timetable.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile timetable.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile timetable.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/timetable1.0.0 || $(MKDIR) .tmp/timetable1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/timetable1.0.0/ && $(COPY_FILE) --parents mainwindow.h authorization.h settings.h order_details.h places.h services.h users.h mheader.h toolbars.h .tmp/timetable1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp authorization.cpp settings.cpp order_details.cpp places.cpp services.cpp users.cpp mheader.cpp .tmp/timetable1.0.0/ && $(COPY_FILE) --parents mainwindow.ui settings.ui order_details.ui places.ui services.ui users.ui authorization.ui .tmp/timetable1.0.0/ && $(COPY_FILE) --parents timetable_ru.ts .tmp/timetable1.0.0/ && (cd `dirname .tmp/timetable1.0.0` && $(TAR) timetable1.0.0.tar timetable1.0.0 && $(COMPRESS) timetable1.0.0.tar) && $(MOVE) `dirname .tmp/timetable1.0.0`/timetable1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/timetable1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_authorization.cpp moc_settings.cpp moc_order_details.cpp moc_places.cpp moc_services.cpp moc_mheader.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_authorization.cpp moc_settings.cpp moc_order_details.cpp moc_places.cpp moc_services.cpp moc_mheader.cpp
moc_mainwindow.cpp: mheader.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_authorization.cpp: authorization.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) authorization.h -o moc_authorization.cpp

moc_settings.cpp: settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settings.h -o moc_settings.cpp

moc_order_details.cpp: order_details.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) order_details.h -o moc_order_details.cpp

moc_places.cpp: places.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) places.h -o moc_places.cpp

moc_services.cpp: services.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) services.h -o moc_services.cpp

moc_mheader.cpp: mheader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mheader.h -o moc_mheader.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_settings.h ui_order_details.h ui_places.h ui_services.h ui_users.h ui_authorization.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_settings.h ui_order_details.h ui_places.h ui_services.h ui_users.h ui_authorization.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_settings.h: settings.ui
	/usr/bin/uic-qt4 settings.ui -o ui_settings.h

ui_order_details.h: order_details.ui
	/usr/bin/uic-qt4 order_details.ui -o ui_order_details.h

ui_places.h: places.ui
	/usr/bin/uic-qt4 places.ui -o ui_places.h

ui_services.h: services.ui
	/usr/bin/uic-qt4 services.ui -o ui_services.h

ui_users.h: users.ui
	/usr/bin/uic-qt4 users.ui -o ui_users.h

ui_authorization.h: authorization.ui
	/usr/bin/uic-qt4 authorization.ui -o ui_authorization.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mheader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mheader.h \
		settings.h \
		places.h \
		services.h \
		authorization.h \
		order_details.h \
		ui_mainwindow.h \
		toolbars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

authorization.o: authorization.cpp authorization.h \
		ui_authorization.h \
		mainwindow.h \
		mheader.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o authorization.o authorization.cpp

settings.o: settings.cpp settings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

order_details.o: order_details.cpp order_details.h \
		ui_order_details.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o order_details.o order_details.cpp

places.o: places.cpp places.h \
		ui_places.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o places.o places.cpp

services.o: services.cpp services.h \
		ui_services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o services.o services.cpp

users.o: users.cpp ui_users.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o users.o users.cpp

mheader.o: mheader.cpp mheader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mheader.o mheader.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_authorization.o: moc_authorization.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_authorization.o moc_authorization.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_order_details.o: moc_order_details.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_order_details.o moc_order_details.cpp

moc_places.o: moc_places.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_places.o moc_places.cpp

moc_services.o: moc_services.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_services.o moc_services.cpp

moc_mheader.o: moc_mheader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mheader.o moc_mheader.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

